package chat.protocol;

public enum Action {
	
	//로그인  
	LOGIN, JOIN, LOGIN_SUCCESS,JOIN_SUCCESS,
	ID_CHECK,ID_CHECK_SUCCESS,ID_CHECK_FAIL,EXIT,
	ID_CHECK_ZERO,
	
	//회원정보
	MODIFY,DELETE,JOIN_FAIL,MODIFY_BASIC,MODIFY_BASIC_OK,
	DELETE_OK,MODIFY_OK,
	
	//채팅관련
	CHAT, CHANGE_USER_LIST ,
	EXIT_SUCCESS, WHISPER, WHISPER_ID,
	CLIENT_EXITIST, ERROR, FILE_SEND_REQUSET;
	
}
